### ISSUE TITLE
Documentação da API

### ISSUE THREAD

**Issue by IncognitaDev** [Lorenalgm/DevChallengeAPI#13]
Acredito que seria interessante que existisse uma documentação da API para ajudar no desenvolvimento e na contribuição para o projeto

**Comment by pedrohram** [comment]
@IncognitaDev 
Está a caminho junto com um update nas docs.

Vamos subir aqui na branch `docs` fazer o Pull Request na `master`, assim ninguém vai precisar ficar trocando de branch para ver a documentação.

Teremos os seguintes itens:
- [x] Readme - com guia de instalação;
- [x] Licença;
- [ ] :construction: Referência de API;
- [ ] :construction: Código de conduta;
- [ ] :construction: Manual de contribuição - precisa ser atualizado.

Você tem tempo para ajudar a desenvolver?

**Comment by IncognitaDev** [comment]
Ajudo sim, vou fazer o fork

**Comment by siqueira-ec** [comment]
Além da documentação no REFERENCE, creio que poderia ser interessante documentar via Swagger também. Só não sei se a melhor decisão seria incluir tudo no mesmo repo ou criar um novo só pra api-docs.
