### ISSUE TITLE
Criação de uma rota UPDATE para os desafios 

### ISSUE THREAD

**Issue by IncognitaDev** [Lorenalgm/DevChallengeAPI#16]
Verifiquei que em há desafios com erros de digitação e acho que seria bom haver uma rota UPDATE para corrigir possíveis erros.

**Você poderia resolver essa Issue com um Pull Request?**
- [ ] Sim, eu tenho tempo e posso começar.
- [ ] Sim, eu tenho tempo mas precisaria de alguém para me direcionar.
- [X] Não, eu não tenho tempo mas poderia solucionar.
- [ ] Não, eu não tenho tempo e não sei por onde começar.

**Comment by Hilverton** [comment]
Para a construção dessa rota deve-se observar qual branch como base?

**Comment by pedrohram** [comment]
Estarei trabalhando nisso.
