### ISSUE TITLE
Implementar testes unitários e testes de integração 

### ISSUE THREAD

**Issue by CristianoPro** [Lorenalgm/DevChallengeAPI#4]
Sugestão!

Seria legal a implementação de teste para garantir um funcionamento correto da api, os teste ajudam na implementação de novas funcionalidades

**Comment by pedrohram** [comment]
Obrigado pela sugestão!

Vamos trabalhar nisso assim que possível.

**Comment by mmouradev** [comment]
Boa ideia, obrigado pela sugestão!

**Comment by pedrohram** [comment]
Fechando a issue devido a inatividade..
